# Generated by Django 5.1.5 on 2025-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('date_release_tickets', models.DateField()),
                ('number_ticket', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
